# Generated by Django 4.2.28 on 2026-02-15 17:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tsc_number', models.CharField(db_index=True, error_messages={'unique': 'A user with this TSC number already exists.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Enter a valid TSC number')])),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with this email address already exists.'}, max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('id_number', models.CharField(db_index=True, error_messages={'unique': 'A user with this ID number already exists.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Enter a valid ID number')])),
                ('full_name', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('user_type', models.CharField(choices=[('VOTER', 'Voter'), ('ADMIN', 'Administrator'), ('SUPER_ADMIN', 'Super Administrator')], default='VOTER', max_length=20)),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected'), ('DELETED', 'Deleted')], default='PENDING', max_length=20)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Review'), ('INCOMPLETE', 'Incomplete Submission')], default='INCOMPLETE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('id_front', models.ImageField(blank=True, max_length=500, null=True, upload_to='kyc/ids/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('id_front_status', models.CharField(choices=[('NOT_UPLOADED', 'Not Uploaded'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_UPLOADED', max_length=20)),
                ('id_back', models.ImageField(blank=True, max_length=500, null=True, upload_to='kyc/ids/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('id_back_status', models.CharField(choices=[('NOT_UPLOADED', 'Not Uploaded'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_UPLOADED', max_length=20)),
                ('face_photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='kyc/faces/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('face_photo_status', models.CharField(choices=[('NOT_UPLOADED', 'Not Uploaded'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_UPLOADED', max_length=20)),
                ('liveness_confidence', models.FloatField(blank=True, null=True)),
                ('liveness_check_passed', models.BooleanField(default=False)),
                ('tsc_verified', models.BooleanField(default=False)),
                ('tsc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('vote_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deletion_requested', models.BooleanField(default=False)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('suspension_lifted_at', models.DateTimeField(blank=True, null=True)),
                ('reset_password_token', models.UUIDField(blank=True, null=True)),
                ('reset_password_sent_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admins', to=settings.AUTH_USER_MODEL)),
                ('deletion_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('kyc_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verified_users', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_users', to=settings.AUTH_USER_MODEL)),
                ('suspension_lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspension_lifted_users', to=settings.AUTH_USER_MODEL)),
                ('tsc_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsc_verified_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_voters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('ACTION_REQUIRED', 'Action Required')], default='INFO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx'), models.Index(fields=['user', 'created_at'], name='accounts_no_user_id_501ff2_idx'), models.Index(fields=['notification_type', 'priority'], name='accounts_no_notific_49417d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['otp', 'is_used'], name='accounts_em_otp_c2c81c_idx'), models.Index(fields=['email', 'is_used'], name='accounts_em_email_16ab31_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('USER', 'User Management'), ('ADMIN', 'Admin Management'), ('ELECTION', 'Election Management'), ('VOTING', 'Voting'), ('KYC', 'KYC Verification'), ('SECURITY', 'Security'), ('SYSTEM', 'System')], default='SYSTEM', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='accounts_au_user_id_d4cccd_idx'), models.Index(fields=['category', 'timestamp'], name='accounts_au_categor_9cc458_idx'), models.Index(fields=['action', 'timestamp'], name='accounts_au_action_11cc52_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('county_of_residence', models.CharField(max_length=100)),
                ('id_document', models.ImageField(upload_to='admin/ids/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('id_back_document', models.ImageField(blank=True, null=True, upload_to='admin/ids/back/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('selfie_photo', models.ImageField(upload_to='admin/faces/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['national_id', 'is_verified'], name='accounts_ad_nationa_b34985_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DELETE', 'Delete Account'), ('SUSPEND', 'Suspend Account'), ('REACTIVATE', 'Reactivate Account'), ('KYC_VERIFY', 'KYC Verification'), ('TSC_VERIFY', 'TSC Verification'), ('DEVICE_RESET', 'Device Reset'), ('ADMIN_APPROVAL', 'Admin Approval'), ('PASSWORD_RESET', 'Password Reset')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_actions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'action_type', 'status'], name='accounts_ac_user_id_9c837d_idx'), models.Index(fields=['requested_at'], name='accounts_ac_request_a986f5_idx'), models.Index(fields=['status', 'action_type'], name='accounts_ac_status_891df7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tsc_number', 'kyc_status'], name='accounts_us_tsc_num_2cfeed_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['device_fingerprint'], name='accounts_us_device__942cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['county', 'school'], name='accounts_us_county_861e30_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'account_status'], name='accounts_us_user_ty_ca89c2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tsc_verified'], name='accounts_us_tsc_ver_6f5d53_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deletion_requested'], name='accounts_us_deletio_e9e49d_idx'),
        ),
    ]
