# Generated by Django 4.2.28 on 2026-02-15 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election_name', models.CharField(default='Teacher Union Elections 2024', max_length=200)),
                ('voting_date', models.DateField(blank=True, null=True)),
                ('voting_start_time', models.TimeField(default='08:00:00')),
                ('voting_end_time', models.TimeField(default='17:00:00')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETUP', 'Setup'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20)),
                ('allow_voting', models.BooleanField(default=False)),
                ('results_published', models.BooleanField(default=False)),
                ('emergency_pause', models.BooleanField(default=False)),
                ('pause_reason', models.TextField(blank=True)),
                ('total_voters', models.IntegerField(default=0)),
                ('total_votes_cast', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Election Setting',
                'verbose_name_plural': 'Election Settings',
            },
        ),
        migrations.CreateModel(
            name='DeviceResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tsc_number', models.CharField(db_index=True, max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('new_device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tsc_number', 'status'], name='core_device_tsc_num_71c679_idx'), models.Index(fields=['created_at'], name='core_device_created_e1521c_idx')],
            },
        ),
    ]
