# Generated by Django 4.2.28 on 2026-02-15 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('bio', models.TextField(blank=True)),
                ('manifesto', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['election', 'position__order', 'order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('election_type', models.CharField(choices=[('NATIONAL', 'National Wide'), ('COUNTY', 'County Based')], default='NATIONAL', max_length=20)),
                ('county', models.CharField(blank=True, help_text='Required only for county-based elections', max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('voting_date', models.DateField(blank=True, null=True)),
                ('voting_start_time', models.TimeField(default='08:00:00')),
                ('voting_end_time', models.TimeField(default='17:00:00')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('allow_voting', models.BooleanField(default=False)),
                ('results_published', models.BooleanField(default=False)),
                ('emergency_pause', models.BooleanField(default=False)),
                ('pause_reason', models.TextField(blank=True)),
                ('total_voters_eligible', models.IntegerField(default=0)),
                ('total_votes_cast', models.IntegerField(default=0)),
                ('auto_open', models.BooleanField(default=True)),
                ('auto_close', models.BooleanField(default=True)),
                ('auto_publish', models.BooleanField(default=False)),
                ('reminder_24h', models.BooleanField(default=True)),
                ('reminder_1h', models.BooleanField(default=True)),
                ('reminder_start', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(default='Default Election', max_length=200)),
                ('voting_date', models.DateField(blank=True, null=True)),
                ('voting_start_time', models.TimeField(default='08:00:00')),
                ('voting_end_time', models.TimeField(default='17:00:00')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('allow_voting', models.BooleanField(default=False)),
                ('results_published', models.BooleanField(default=False)),
                ('emergency_pause', models.BooleanField(default=False)),
                ('pause_reason', models.TextField(blank=True)),
                ('total_voters', models.IntegerField(default=0)),
                ('total_votes_cast', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Legacy Election Setting',
                'verbose_name_plural': 'Legacy Election Settings',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_hash', models.CharField(max_length=256, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_fingerprint', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vote_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('candidates', models.ManyToManyField(related_name='votes', to='voting.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('color_code', models.CharField(default='#000000', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='voting.election')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_votes', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('require_team', models.BooleanField(default=False)),
                ('require_manifesto', models.BooleanField(default=False)),
                ('require_bio', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='voting.election')),
            ],
            options={
                'ordering': ['election', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_applications/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='voting.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applications', to='voting.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='voting.position')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='voting.team')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidate', to='voting.candidateapplication'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.position'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='voting.team'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidacies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VoteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VOTE_CAST', 'Vote Cast'), ('VOTE_VERIFIED', 'Vote Verified'), ('VOTE_INVALIDATED', 'Vote Invalidated'), ('BALLOT_OPENED', 'Ballot Opened'), ('BALLOT_CLOSED', 'Ballot Closed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(default=dict)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='voting.election')),
                ('vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='voting.vote')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['election', 'action', 'timestamp'], name='voting_vote_electio_0e9636_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'timestamp'], name='voting_vote_electio_d098cf_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter', 'election'], name='voting_vote_voter_i_23041b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('election', 'voter')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['election', 'status'], name='voting_team_electio_90ff1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('election', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('election', 'order')},
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status', 'voting_date'], name='voting_elec_status_bb6fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['election_type', 'county'], name='voting_elec_electio_d44473_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateapplication',
            index=models.Index(fields=['election', 'status'], name='voting_cand_electio_e74deb_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateapplication',
            index=models.Index(fields=['voter', 'election'], name='voting_cand_voter_i_52d466_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateapplication',
            unique_together={('election', 'voter', 'position')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'position', 'vote_count'], name='voting_cand_electio_fbca70_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'team'], name='voting_cand_electio_461056_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'position', 'full_name')},
        ),
    ]
